### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by bizip**
What does this PR do?

- This PR Create a responsive landing page

- Configuring ESlint for react

- Rise all test coverage up to 100%

- Create a responsive landing page

- Add useful links like help and accommodation

- Add text describing the purpose of the landing page

Description of Task  completed

All the task are completed

How should this be manually tested?

- clone the Branch

- run `npm install`

- run `npm run build:css` to build tailwind css

-  run `npm run dev` to build tailwind css

Any background context you want to provide?

- We still processing or writting the test that will be covered on 11 December 2020

What are the relevant Trello story?

- Feature Landing page  https://trello.com/c/vv6wuEPH

### CODE REVIEW

**Comment by mugisha1555** [comment]
looks great thank you Pisco, lets fix the test that is not passing

**Review by mugisha1555 — COMMENTED** [review]
great work boss! Let's work on the only one test that is not running

**Review by mukunzidd — CHANGES_REQUESTED** [review]
Add changes as per our 1:1

**Comment by bizip** [comment]
> Add changes as per our 1:1

I have tried

**Review by muhireheir — APPROVED** [review]
Approved

**Review by mukunzidd — APPROVED** [review]

**Comment by mukunzidd** [comment]
@bizip rename the GitHub Actions workflow file to just be `ci.yml` and the workflow name to be `"CI"` instead of NodeJS CI. It doesn't make sense in a react project. Then work with @nkalyesubula to merge this PR.

**Review by nkalyesubula — APPROVED** [review]
Looks good to me

**Pull request merged**
